export const LOADER_DRAW_DURATION = 500;
export const LOADER_HOLD_DURATION = 150;
export const LOADER_EXPAND_DURATION = 350;
export const LOADER_TOTAL_DURATION =
  LOADER_DRAW_DURATION + LOADER_HOLD_DURATION + LOADER_EXPAND_DURATION;
export const LOADER_REDUCED_MOTION_DURATION = 500;
